foodgram/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("ingredients", views.Ingredients.as_view(), name="ingredients"),
    path("favorites", views.Favorites.as_view(), name="add_favor"),
    path(
        "favorites/<int:recipe_id>",
        views.Favorites.as_view(),
        name="remove_favor"
    ),
    path("subscriptions", views.Subscription.as_view(), name="add_subs"),
    path(
        "subscriptions/<int:author_id>",
        views.Subscription.as_view(),
        name="remove_subs",
    ),
    path(
        "purchases",
        views.Purchases.as_view(),
        name="add_to_shop"
    ),
    path(
        "purchases/<int:recipe_id>",
        views.Purchases.as_view(),
        name="remove_from_shop"
    ),
]

foodgram/foodgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include("django.contrib.auth.urls")),
    path('api/', include('api.urls')),
    path('', include('recipe.urls'))
]

urlpatterns += [
        path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
        path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
        path(
            'about-author/',
            views.flatpage,
            {'url': '/about-author/'},
            name='author'
        ),
        path(
            'about-spec/',
            views.flatpage,
            {'url': '/about-spec/'},
            name='spec'
        ),
]

foodgram/recipe/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path("recipe/<username>/", views.profile, name='profile'),
    path('new-recipe', views.new_recipe, name='new_recipe'),
    path(
        'recipe/<int:recipe_id>/edit',
        views.recipe_edit,
        name='recipe_edit'
    ),
    path(
        'recipe/<int:recipe_id>/delete',
        views.recipe_delete,
        name='recipe_delete'
    ),
    path(
        'recipe/<username>/<int:recipe_id>/',
        views.recipe_view,
        name='recipe_view'
    ),
    path("follow/<username>/", views.follow, name='follow'),
    path('followrecipe/<username>/', views.follow_recipe, name='followrecipe'),
    path('shopping-list/', views.shopping_list, name='shopping-list'),
    path('download', views.download, name='download'),
]

foodgram/recipe/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(
        verbose_name='Название ингредиента',
        max_length=255,
        null=True,
        blank=True
    )
    dimension = models.CharField(
        verbose_name='Количество',
        max_length=255,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(verbose_name='Имя тега', max_length=255)
    value = models.CharField(verbose_name='Значение тега', max_length=50)
    color = models.CharField(verbose_name='цвет', max_length=30, null=True)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(verbose_name='Название рецепта', max_length=255)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='Recipe'
    )
    image = models.ImageField(upload_to='recipe/', blank=True, null=True)
    description = models.TextField(verbose_name='Описание')
    cooking_time = models.IntegerField(verbose_name='Время приготовления')
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    ingredients = models.ManyToManyField(
        Ingredient,
        through='RecipeIngredients',
        through_fields=('recipe', 'ingredient')
    )
    tag = models.ManyToManyField(Tag)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']


class RecipeIngredients(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name='Ingredient'
    )
    amount = models.IntegerField()

    def __str__(self):
        return self.ingredient.dimension


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower"
        )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
        )

    def __str__(self):
        return self.user.username


class FollowRecipe(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favor_by'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='favor'
    )

    def __str__(self):
        return self.follow_recipe.title


class ShoppingList(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='shopper'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='shopping_list'
    )

    def __str__(self):
        return self.recipe.title

foodgram/recipe/forms.py
from django.forms import ModelForm, CheckboxSelectMultiple

from recipe.models import Recipe


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'image', 'tag', 'cooking_time', 'description')
        widgets = {'tag': CheckboxSelectMultiple()}

foodgram/recipe/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .forms import RecipeForm
from .models import (
    Recipe,
    Ingredient,
    User,
    Follow,
    ShoppingList,
    RecipeIngredients
)
from .utils import gen_shopping_list, get_ingredients


# Количество рецептов на странице
PAGES = 9


def index(request):
    tag = request.GET.getlist('filters')
    recipe_list = Recipe.objects.all()
    if tag:
        recipe_list = recipe_list.filter(tag__value__in=tag).distinct().all()
    paginator = Paginator(recipe_list, PAGES)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(
        request,
        'index.html',
        {'page': page, 'paginator': paginator, }
    )


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    tag = request.GET.getlist('filters')
    recipe_list = Recipe.objects.filter(author=profile.pk).all()
    if tag:
        recipe_list = recipe_list.filter(tag__value__in=tag)
    paginator = Paginator(recipe_list, PAGES)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'profile.html',
        {
            'profile': profile,
            'recipe_list': recipe_list,
            'page': page,
            'paginator': paginator
        }
    )


@login_required
def new_recipe(request):
    user = User.objects.get(username=request.user)
    if request.method == 'POST':
        form = RecipeForm(request.POST or None, files=request.FILES or None)
        ingredients = get_ingredients(request)
        if not ingredients:
            form.add_error(None, 'Добавьте ингредиенты')
        elif form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = user
            recipe.save()
            for ing_name, amount in ingredients.items():
                ingredient = get_object_or_404(Ingredient, title=ing_name)
                recipe_ing = RecipeIngredients(
                    recipe=recipe,
                    ingredient=ingredient,
                    amount=amount
                )
                recipe_ing.save()
            form.save_m2m()
            return redirect('index')
    else:
        form = RecipeForm()
    return render(request, 'new_recipe.html', {'form': form})


@login_required
def recipe_edit(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user != recipe.author:
        return redirect('recipe', recipe_id=recipe.id)
    if request.method == "POST":
        form = RecipeForm(
            request.POST or None,
            files=request.FILES or None,
            instance=recipe
        )
        ingredients = get_ingredients(request)
        if form.is_valid():
            RecipeIngredients.objects.filter(recipe=recipe).delete()
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            recipe.ingredients.all().delete()
            for ing_name, amount in ingredients.items():
                ingredient = get_object_or_404(Ingredient, title=ing_name)
                recipe_ing = RecipeIngredients(
                    recipe=recipe,
                    ingredient=ingredient,
                    amount=amount
                )
                recipe_ing.save()
            form.save_m2m()
            return redirect('index')
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    return render(
        request,
        'change_recipe.html',
        {'form': form, 'recipe': recipe, }
    )


def recipe_view(request, recipe_id, username):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    profile = get_object_or_404(User, username=username)
    return render(
        request,
        'recipe.html',
        {'profile': profile, 'recipe': recipe, }
    )


@login_required
def recipe_delete(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user == recipe.author:
        recipe.delete()
    return redirect('index')


@login_required
def follow(request, username):
    user = get_object_or_404(User, username=username)
    author_list = Follow.objects.filter(user=user).all()
    paginator = Paginator(author_list, PAGES)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'follow.html',
        {'page': page, 'paginator': paginator, 'authors': author_list}
    )


@login_required
def follow_recipe(request, username):
    tag = request.GET.getlist('filters')
    recipe_list = Recipe.objects.filter(favor__user__id=request.user.id).all()
    if tag:
        recipe_list = recipe_list.filter(tag__value__in=tag).distinct()
    paginator = Paginator(recipe_list, PAGES)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'favorite.html',
        {'page': page, 'paginator': paginator, }
    )


def shopping_list(request):
    shopping_list = ShoppingList.objects.filter(user=request.user).all()
    return render(
        request,
        'shopping-list.html',
        {'shopping_list': shopping_list}
    )


@login_required
def download(request):
    result = gen_shopping_list(request)
    filename = 'ingredients.txt'
    response = HttpResponse(result, content_type='text/plain')
    response['Content-Disposition'] = \
        'attachment; filename={0}'.format(filename)
    return response

foodgram/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title%}Регистрация{% endblock%}</title>
        {% load static %}
        {% csrf_token %}
        {% block static %}
        <link rel="stylesheet" href="{% static 'pages/form.css' %}">
        {% endblock %}
    </head>
    <body>
        <header class="header">
            <nav class="nav">
                <div class="nav__container container">
                    {% if user.is_authenticated %}
                    <ul class="nav__items list">
                        {% block index %}<li class="nav__item">{% endblock %}<a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                        {% block subs %}<li class="nav__item">{% endblock %}<a href="{% url 'follow' user.username %}" class="nav__link link">Мои подписки</a></li>
                        {% block new_recipe %}<li class="nav__item">{% endblock %}<a href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                        {% block favorites %}<li class="nav__item">{% endblock %}<a href="{% url 'followrecipe' user.username %}" class="nav__link link">Избранное</a></li>
                        {% block shop %}<li class="nav__item">{% endblock %}<a href="{% url 'shopping-list' %}" class="nav__link link">Список покупок</a> <span  class="badge badge_style_blue nav__badge" id="counter">{% if count %}{{ count }}{% endif %}</span></li>
                    </ul>
                    <ul class="nav__items list">
                        {% block pass_change %}<li class="nav__item">{% endblock %}<a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                        <li class="nav__item"><a href="{% url 'logout'%}" class="nav__link link">Выход</a></li>
                    </ul>
                    {% else %}
                    <ul class="nav__items list">
                        <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                    </ul>
                    <ul class="nav__items list">
                        {% block login %}<li class="nav__item">{% endblock %}<a href="{% url 'login'%}" class="nav__link link">Войти</a></li>
                        {% block create_acc %}<li class="nav__item">{% endblock %}<a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
                    </ul>
                    {% endif %}
                </div>
            </nav>
        </header>
    <main>
            <div class="container">
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock content %}
            </div>
        </main>
        {% include 'footer.html' %}
    </body>
</html>

foodgram/templates/buy_button.html
{% load user_filter %}
                
                {% if user.is_authenticated %}
                {% if recipe|is_shop:user %}
                        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
                    {% else %}
                        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
                    {% endif %}
                {% endif %}

foodgram/templates/change_recipe.html
{% extends 'base.html' %}
{% block title%} Изменить рецепт {% endblock%}
    {% load static %}
    {% csrf_token %}
        {% load static %}
        {% block static %}
        <link rel="stylesheet" href={% static 'pages/form.css' %}>
        {% endblock %}
{% load user_filter %}
{% block content %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    {{ form.errors }}
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="{{ form.name.id_for_label }}" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }} 
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag_choice, tag_value in form.tag.field.choices %}
                        <div class="tags__item">
                            <input 
                                type="checkbox" 
                                name="tag" 
                                value = "{{ tag_choice.instance.pk }}"
                                id="id_{{ tag_choice.instance.value }}" 
                                class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}">
                            <label for="id_{{ tag_choice.instance.value }}" class="tags__label">{{ tag_choice.instance.name }}</label>
                        </div>
                    {% endfor %}
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container"></div>
                    
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time|addclass:"form__input" }}
                    <label for="id_time" class="form__label">минут</label>
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="{{ form.text.id_for_label }}" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description|addclass:"form__textarea" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {{ form.image|addclass:"form__file-button" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Сохранить рецепт</button>
                <a style="margin-left: 2.5em" href="{% url 'recipe_delete' recipe.id %}" class="single-card__text">Удалить рецепт</a></li>
            </div>
        </form>
    </div>


</main>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/formRecipe.js' %}"></script>
{% endblock %}

foodgram/templates/favor_button.html
{% load user_filter %}

{% if user.is_authenticated %}
    {% if recipe|is_favorite:user %}
        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
    {% else %}
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    {% endif %}
{% endif %}

foodgram/templates/favorite.html
{% extends 'base.html' %}
{% block title%} Избранное {% endblock%}
    {% load static %}
    {% block favorites %} <li class="nav__item nav__item_active"> {% endblock %}
    {% csrf_token %}
    {% block static %}
    <link rel="stylesheet" href={% static 'pages/index.css' %}>
    {% endblock %}
    {% load user_filter %}
    {% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
            <ul class="tags">
                {% for tag in all_tags %}
                        <li class="tags__item">
                            <a
                                id="{{ tag.pk }}"
                                class="tags__checkbox tags__checkbox_style_{{ tag.color }}
                                {% if tag.value in request.GET|get_filter_values %} tags__checkbox_active {% endif %}"
                                href="{% url 'followrecipe' request.user.username %}?{{ request|get_filter_link:tag }}"></a>
                            <span class="tags__label">{{ tag.name }}</span>
                        </li>
                    {% endfor %}
            </ul>
        </div>
        <div class="card-list">
            
            {% for recipe in page %}
                {% include 'recipe_item.html' %}
            {% endfor %}
        </div>
            {% if page.has_other_pages %}
                {% include 'paginator.html' %}
            {% endif %}
    </main>
 
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/favorite.js' %}"></script>

{% endblock %} 

foodgram/templates/follow.html
{% extends 'base.html' %}
{% block title%} Мои подписки {% endblock%}
    {% load static %}
    {% csrf_token %}
    {% block subs %} <li class="nav__item nav__item_active"> {% endblock %}
    {% block static %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
    {% endblock %}
    {% load user_filter %}
    {% block content %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for item in page %}
        <div class="card-user" data-author="{{ item.author.id }}">
            <div class="card-user__header">
                <h2 class="card-user__title"> {{ item.author.username }} </h2>
            </div>
            <div class="card-user__body">
                <ul class="card-user__items">
                        {% for recipe in item.author.Recipe.all|slice:":3" %}
                                <li class="card-user__item">
                                    <div class="recipe">
                                        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe__image">
                                        <h3 class="recipe__title">{{ recipe.title }}</h3>
                                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                                    </div>
                                </li>
                        {% endfor %}
                    <li class="card-user__item">
                        <a href="{% url 'profile' item.author.username %}" class="card-user__link link">Еще...</a>
                    </li>
                </ul>
            </div>
            <div class="card-user__footer">
                <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться </button>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if page.has_other_pages %}
    {% include 'paginator.html' %}
    {% endif %} 
</main>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/myFollow.js' %}"></script>


{% endblock %}

foodgram/templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'spec' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

foodgram/templates/recipe.html
{% extends 'base.html' %}
{% block title%} {{ recipe.title }} {% endblock%}
    {% load static %}
    {% csrf_token %}
    {% block static %}
    <link rel="stylesheet" href={% static 'pages/single.css' %}>
    {% endblock %}
    {% load user_filter %}
    {% block content %}
    <main class="main container">
        <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ profile.id }}">
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="single-card__image"></a>
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title"> {{ recipe.title }} </h1>
                    <div class="single-card__favorite">
                        {% include 'favor_button.html' %}
                    </div>
                </div>
                <ul class="single-card__items">
                    <ul class="card__items">
                        {% for tag in recipe.tag.all %}
                        <span class="badge badge_style_{{ tag.color }}">{{ tag.name }}</span></li>
                        {% endfor %}
                    </ul>
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{recipe.cooking_time}} мин.</p>
                    <ul class="single-card__items">
                        <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author.username %}" style="color: black">{{ recipe.author.first_name }}</a></p>
                        {% if user == recipe.author %}
                        <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipe_edit' recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                        {% endif %}
                    </ul>
                </div>
                <ul class="single-card__items">
                    {% include 'buy_button.html' %}
                    {% if user.username != profile.username %}
                    {% if user.is_authenticated %}
                        {% if recipe.author|is_follow:user %}
                        <li class="single-card__item"><button class="button button_style_light-blue button_size_auto" name="subscribe"><span class="icon-check button__icon"></span> Отписаться от автора </button>
                        {% else %}
                        <li class="single-card__item"><button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></li>
                        {% endif %}
                        {% endif %}
                    {% endif %}
                </ul>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингредиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ing in recipe.recipeingredients_set.all %}
                        <p class=" single-card__section-item">{{ ing.ingredient.title }} - {{ ing.amount }} {{ ing.ingredient.dimension }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description }}</p>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/config/config.js' %}"></script>
    {% if user.is_authenticated %}
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/singlePage.js' %}"></script>
    {% else %}
    <script src="{% static 'js/components/Purchases.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/singlePageNotAuth.js' %}"></script>
    {% endif %}
    {% endblock %}

foodgram/templates/recipe_item.html
<div class="card" data-id="{{ recipe.id }}">
    <a href="{% url 'recipe_view' recipe.author.username recipe.id %}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe_view' recipe.author.username recipe.id %}" target="_blank"> {{ recipe.title }}</a> 
        <ul class="card__items">
            {% for tag in recipe.tag.all %}
            <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.name }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author.username %}" style="color: black">{{ recipe.author.username }}</a></p>
        </div>
    </div>
    <div class="card__footer">
        {% include 'buy_button.html' %}
        {% include 'favor_button.html' %}
    </div>
</div>